apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: iqrazafar865/scdfinal:event-bus-image
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  type: LoadBalancer
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
