apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: iqrazafar865/scdfinal:moderation-image
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
spec:
  type: LoadBalancer
  selector:
    app: moderation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
