apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: iqrazafar865/scdfinal:posts-image
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  type: LoadBalancer
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
