apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: iqrazafar865/scdfinal:query-image
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  type: LoadBalancer
  selector:
    app: query
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
